name = "MusicAlbums"
uuid = "b7b9ff52-2528-4e0e-b86f-a161620f4c01"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com>"]
version = "0.1.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
ExpiringCaches = "bd5c46ae-da38-4b10-bcdd-5005402f2c4f"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JWTs = "d850fbd6-035d-5a70-a269-1ca2e636ac6c"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
Strapping = "3787371a-436b-4cb0-be6b-e772a55e3ebe"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
