name = "MusicAlbums"
uuid = "b7b9ff52-2528-4e0e-b86f-a161620f4c01"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
